### ISSUE TITLE
bug: lambda on write on channel attributes

### ISSUE THREAD

**Issue by srgblnch** [srgblnch/skippy#12]

**Comment by srgblnch** [comment]
Traceback (most recent call last):
  File "/homelocal/sicilia/ds/python/skippy/instructionSet.py", line 125, in nestedMethod
    return function(inst, attr, *args, **kwargs)
  File "skippy.py", line 1003, in write_attr
    self.__write_instrument_attr(attr, attrName, data)
  File "skippy.py", line 1021, in __write_instrument_attr
    cmd = self.attributes[attrName].writeCmd(data[0])
TypeError: <lambda>() takes exactly 2 arguments (1 given)

There is an error in the attribute build when there are channels.

**Comment by srgblnch** [comment]
While testing we've seen that doing "read_attributes([...])" the device is asking all in one query (as expected) but then reasks for each one.

>>> import PyTango
>>> dev = PyTango.DeviceProxy("test/ct/alba-em2")
>>> dev.read_attributes(['CurrentCh3','CurrentCh2'])

The logs of the device are:

1500370655 [140469804116304] DEBUG test/ct/alba-em2 Asking: 'CHAN03:CURRent?;CHAN02:CURRent?;'
1500370655 [140469804116304] DEBUG test/ct/alba-em2 Answer: '[];[]\r\n'
1500370655 [140469804116304] DEBUG test/ct/alba-em2 In __read_attr_procedure() scalar answers: "'[];[]\\r\\n'"
1500370655 [140469804116304] DEBUG test/ct/alba-em2 Asking: 'CHAN03:CURRent?'
1500370655 [140469804116304] DEBUG test/ct/alba-em2 Answer: '[]\r\n'
1500370655 [140469804116304] DEBUG test/ct/alba-em2 Asking: 'CHAN02:CURRent?'
1500370655 [140469804116304] DEBUG test/ct/alba-em2 Answer: '[]\r\n'
